### PR TITLE
Integration with Gravity PDF

### PR DESCRIPTION
**Pull request by lukecav**

### CODE REVIEW

**Comment by 13pixlar** [comment]
Thanks for the PL @lukecav. Unfortunately, I cannot merge this automatically since you seem to have removed all the code comments from [6fa97bd](https://github.com/13pixlar/sticky-list/pull/10/commits/6fa97bd83ddff1795005bd5d148a186f7d7251c2)

**Comment by lukecav** [comment]
I will fix.

**Comment by 13pixlar** [comment]
I still cant merge this pull request because of missing comments. I have tired your code and it seems to work well. However, maybe we should do a check to see if the PDF-addon is active, and if it is not we should gray out/disable the option to activate it.

**Comment by lukecav** [comment]
I will fix the comments issue if I can this week.

**Comment by 13pixlar** [comment]
I would like to merge this... :)

**Comment by 13pixlar** [comment]
This has now been implemented. Did not merge your pull request but was inspired by it. Thanks.

**Comment by lukecav** [comment]
@13pixlar 

Great to hear.

**Pull request closed without merging**
